export const kaasitomaPaths = {
    loginPath: "/login",
    addReceiverAccountPath: "/kaasitoma/receiver-accounts/add-receiver-account",
    applyForTransferPath: "/kaasitoma/transfer-requests/apply-for-transfer?receiverAccountId=",
    receiverAccountsPath: "/kaasitoma/receiver-accounts",
    receiverAccountDetailsPath: "/kaasitoma/receiver-accounts/details?receiverAccountId=",
    sendingRecordsPath: "/kaasitoma/sending-records",
    transferRequestsPath: "/kaasitoma/transfer-requests",
    settledTransfersPath: "/kaasitoma/settled-transfers",
    topUpRequestsPath: "/kaasitoma/top-up",
    topUpDetailsPath: "/kaasitoma/top-up/details",
    topUpCountryAndMethodPath: "/kaasitoma/top-up/country-and-method?receiverAccountId=",
    topUpInstructionsPath: "/kaasitoma/top-up/instructions?",
    topUpRequestDetailsPath: "/kaasitoma/top-up/request-details",
}